nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200'] 
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'X-AUTH-TOKEN']
        expose_headers: []
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/': ~
